name: configstore
on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 'coverage-3.9'
          - '3.8'
          - '3.7'
          - 'check-3.9'
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Determine Python version
        id: get-python-version
        run: |
          echo ::set-output name=value::\
          $(echo ${{ matrix.python-version }} | grep -q 3.9 && echo 3.9 || echo ${{ matrix.python-version }} )
      - name: Set up Python ${{ steps.get-python-version.outputs.value }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ steps.get-python-version.outputs.value }}
      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: configstore-v1-${{ hashFiles('pyproject.toml') }}
          restore-keys: configstore-v1-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        run: tox

  slack-workflow-status:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test
    steps:
      - name: Send Slack notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
